### PR TITLE
[App] Set Ictus logo in NavigationBar & Login screen

### LINKED ISSUE #30: Add ICTUS logo to the app
logo-ictusnet

More details to come

### PR DESCRIPTION
**Pull request by BPierrick**
## Fixes

- Fixes #30 

## Captures

Capture d’écran 2021-12-09 à 14 25 55

Capture d’écran 2021-12-09 à 12 17 28

## Definition of Done

- [x] I followed the [Arkhn Code Book](https://www.notion.so/arkhn/Arkhn-Code-Book-23ac18a8af7343d0a3f61f1c9ef7400c) (I swear!).
- [x] I have written tests for the code I added or updated.
- [x] I have updated the documentation according to my changes.
- [x] I have updated the deployment configuration if needed.

### CODE REVIEW

**Review by elsiehoffet-94 — APPROVED** [review]
Great, thanks! Could you also add the image to the readme please ?

**Review by tevariou — APPROVED** [review]
👍

**Comment by BPierrick** [comment]
> Great, thanks! Could you also add the image to the readme please ?

It's already done in the readme located a the root of this repo 🤔

Do you mean another readme ?

**Comment by elsiehoffet-94** [comment]
> > Great, thanks! Could you also add the image to the readme please ?
> 
> It's already done in the readme located a the root of this repo 🤔
> 
> Do you mean another readme ?

Oops sorry I didn't see it :) It's all perfect then 🚀

**Pull request merged**
